import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import './lib/fontawesome';

const kanit = Kanit({
  subsets: ["latin"], // include other subsets if needed
  weight: ["100", "200", "300", "400", "500", "600", "700"], // choose needed weights
  variable: "--font-kanit", // optional for CSS variable usage
});

export const metadata: Metadata = {
  title: "The University Of Thai Chamber Of Commerce",
  // description: "Generated by create next app",
  icons: {
    icon: "/UTCC-Official-1.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>{children}</body>
    </html>
  );
}
